version: "3.9"

services:
  employee-api:
    build: .
    container_name: employee_api
    ports:
      - "8080:8080"
    environment:
      SCYLLA_HOST: "${SCYLLA_HOST}"
      SCYLLA_PORT: "9042"
      SCYLLA_KEYSPACE: "employee_db"
      REDIS_HOST: "${REDIS_HOST}"
      REDIS_PORT: "6379"
