version: "3.9"

services:
  scylla:
    image: scylladb/scylla:5.4
    container_name: scylla
    command: --smp 1 --memory 750M --overprovisioned 1
    ports:
      - "9042:9042"
    volumes:
      - scylla-data:/var/lib/scylla
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "DESCRIBE KEYSPACES"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  migrate:
    image: cassandra:4.1
    container_name: migrate
    depends_on:
      scylla:
        condition: service_healthy
    volumes:
      - ./migrations:/migrations
    entrypoint: /bin/bash
    command: |
      -c "
      echo 'Waiting for Scylla...'
      until cqlsh scylla -e 'DESCRIBE KEYSPACES' > /dev/null 2>&1; do
        echo 'Scylla not ready, retrying...'
        sleep 5
      done
      echo 'Creating keyspace if missing...'
      cqlsh scylla -e \"
        CREATE KEYSPACE IF NOT EXISTS employee_db
        WITH replication = {'class':'SimpleStrategy','replication_factor':1'};
      \"
      echo 'Running migrations...'
      for f in /migrations/*.cql; do
        [ -e \"$f\" ] || continue
        echo \"Applying $f...\"
        cqlsh scylla -f \"$f\"
      done
      echo 'Migrations completed.'
      "
    restart: "on-failure"

  employee-api:
    build: .
    container_name: employee-api
    depends_on:
      - migrate
      - redis
    ports:
      - "8080:8080"
    environment:
      SCYLLA_HOST: "scylla"
      SCYLLA_PORT: "9042"
      SCYLLA_KEYSPACE: "employee_db"

volumes:
  scylla-data:
  redis-data:
